CREATE DATABASE Healthcare_Medical_Recruitment;

USE Healthcare_Medical_Recruitment;

CREATE TABLE Jobs (
    Job_Id INT PRIMARY KEY,
    Institution_Name VARCHAR(120) NOT NULL,
    Job_Type VARCHAR(20) NOT NULL,
    Department VARCHAR(100) NOT NULL,
    Job_Role VARCHAR(50) NOT NULL,
    Specialization VARCHAR(100) NOT NULL,
    Location VARCHAR(80) NOT NULL,
    Posted_Date DATE NOT NULL,
    Vacancy_Count INT NOT NULL,
    Status VARCHAR(20) NOT NULL
);

INSERT INTO Jobs
(Job_Id, Institution_Name, Job_Type, Department, Job_Role, Specialization, Location, Posted_Date, Vacancy_Count, Status)
VALUES
(101, 'AIIMS New Delhi', 'College', 'Anatomy', 'Assistant Professor', 'Anatomy', 'Delhi', '20260110', 2, 'Open'),
(102, 'AIIMS New Delhi', 'College', 'Physiology', 'Associate Professor', 'Physiology', 'Delhi', '20260112', 1, 'Open'),
(103, 'AIIMS New Delhi', 'College', 'Biochemistry', 'Assistant Professor', 'Biochemistry', 'Delhi', '20260115', 2, 'Open'),
(104, 'Maulana Azad Medical College', 'College', 'General Medicine', 'Professor', 'Internal Medicine', 'Delhi', '20260118', 1, 'Open'),
(105, 'Maulana Azad Medical College', 'College', 'Pathology', 'Senior Resident', 'Pathology', 'Delhi', '20260120', 3, 'Open'),
(106, 'Lady Hardinge Medical College', 'College', 'Pharmacology', 'Assistant Professor', 'Pharmacology', 'Delhi', '20260122', 2, 'Open'),
(107, 'Lady Hardinge Medical College', 'College', 'Microbiology', 'Senior Resident', 'Microbiology', 'Delhi', '20260124', 2, 'Open'),
(108, 'University College of Medical Sciences', 'College', 'Community Medicine', 'Associate Professor', 'Community Medicine', 'Delhi', '20260126', 1, 'Open'),
(109, 'VMMC and Safdarjung Medical College', 'College', 'Ophthalmology', 'Assistant Professor', 'Ophthalmology', 'Delhi', '20260128', 2, 'Open'),
(110, 'VMMC and Safdarjung Medical College', 'College', 'ENT', 'Senior Resident', 'Otorhinolaryngology', 'Delhi', '20260130', 3, 'Open'),
(111, 'KGMU Lucknow', 'College', 'Paediatrics', 'Professor', 'Paediatrics', 'Lucknow', '20260201', 1, 'Open'),
(112, 'KGMU Lucknow', 'College', 'Radiology', 'Associate Professor', 'Radio Diagnosis', 'Lucknow', '20260203', 1, 'Open'),
(113, 'KGMU Lucknow', 'College', 'Psychiatry', 'Assistant Professor', 'Psychiatry', 'Lucknow', '20260205', 2, 'Open'),
(114, 'Dr. Ram Manohar Lohia Medical College', 'College', 'Medicine', 'Senior Resident', 'Internal Medicine', 'Lucknow', '20260207', 3, 'Open'),
(115, 'Dr. Ram Manohar Lohia Medical College', 'College', 'Surgery', 'Senior Resident', 'General Surgery', 'Lucknow', '20260209', 3, 'Open'),
(116, 'Dr. Ram Manohar Lohia Medical College', 'College', 'Orthopaedics', 'Assistant Professor', 'Orthopaedics', 'Lucknow', '20260211', 2, 'Open'),
(117, 'Seth GS Medical College', 'College', 'Dermatology', 'Professor', 'Dermatology', 'Mumbai', '20260213', 1, 'Open'),
(118, 'Seth GS Medical College', 'College', 'Obstetrics & Gynaecology', 'Associate Professor', 'OBG', 'Mumbai', '20260215', 1, 'Open'),
(119, 'Grant Medical College', 'College', 'Ophthalmology', 'Assistant Professor', 'Ophthalmology', 'Mumbai', '20260219', 2, 'Open'),
(120, 'Grant Medical College', 'College', 'Microbiology', 'Senior Resident', 'Microbiology', 'Mumbai', '20260221', 3, 'Open'),
(121, 'Tata Memorial Hospital (Medical College wing)', 'College', 'Medical Oncology', 'Assistant Professor', 'Medical Oncology', 'Mumbai', '20260223', 2, 'Open'),
(122, 'Tata Memorial Hospital (Medical College wing)', 'College', 'Surgical Oncology', 'Associate Professor', 'Surgical Oncology', 'Mumbai', '20260225', 1, 'Closed'),
(123, 'JJ Group of Hospitals (Medical College wing)', 'College', 'Paediatrics', 'Senior Resident', 'Paediatrics', 'Mumbai', '20260227', 3, 'Open'),
(124, 'Lilavati Hospital (College-affiliated)', 'College', 'Cardiology', 'Assistant Professor', 'Cardiology', 'Mumbai', '20260228', 2, 'Open'),
(125, 'Stanley Medical College', 'College', 'Medicine', 'Professor', 'Internal Medicine', 'Chennai', '20260301', 1, 'Open'),
(126, 'Stanley Medical College', 'College', 'Surgery', 'Senior Resident', 'General Surgery', 'Chennai', '20260303', 3, 'Open'),
(127, 'Stanley Medical College', 'College', 'Dermatology', 'Assistant Professor', 'Dermatology', 'Chennai', '20260305', 2, 'Open'),
(128, 'Madras Medical College', 'College', 'Paediatrics', 'Associate Professor', 'Paediatrics', 'Chennai', '20260307', 1, 'Open'),
(129, 'Madras Medical College', 'College', 'Anaesthesia', 'Senior Resident', 'Anaesthesiology', 'Chennai', '20260309', 3, 'Open'),
(130, 'Madras Medical College', 'College', 'Radiology', 'Assistant Professor', 'Radio Diagnosis', 'Chennai', '20260311', 2, 'Open'),
(131, 'Government Kilpauk Medical College', 'College', 'Orthopaedics', 'Professor', 'Orthopaedics', 'Chennai', '20260313', 1, 'Open'),
(132, 'Government Kilpauk Medical College', 'College', 'General Medicine', 'Senior Resident', 'Internal Medicine', 'Chennai', '20260315', 3, 'Open'),
(133, 'B.J. Medical College', 'College', 'ENT', 'Associate Professor', 'Otorhinolaryngology', 'Ahmedabad', '20260317', 1, 'Open'),
(134, 'B.J. Medical College', 'College', 'Dermatology', 'Senior Resident', 'Dermatology', 'Ahmedabad', '20260319', 3, 'Open'),
(135, 'B.J. Medical College', 'College', 'Radiology', 'Assistant Professor', 'Radio Diagnosis', 'Ahmedabad', '20260321', 2, 'Open'),
(136, 'B.J. Medical College', 'College', 'Medicine', 'Professor', 'Internal Medicine', 'Ahmedabad', '20260323', 1, 'Closed'),
(137, 'Government Medical College Kozhikode', 'College', 'Psychiatry', 'Senior Resident', 'Psychiatry', 'Kozhikode', '20260325', 3, 'Open'),
(138, 'Government Medical College Kozhikode', 'College', 'Dermatology', 'Assistant Professor', 'Dermatology', 'Kozhikode', '20260327', 2, 'Open'),
(139, 'Government Medical College Kottayam', 'College', 'Medicine', 'Senior Resident', 'Internal Medicine', 'Kottayam', '20260329', 3, 'Open'),
(140, 'Amrita School of Medicine', 'College', 'Nephrology', 'Assistant Professor', 'Nephrology', 'Kochi', '20260331', 2, 'Open'),
(141, 'Amrita School of Medicine', 'College', 'Cardiology', 'Associate Professor', 'Cardiology', 'Kochi', '20260402', 1, 'Open'),
(142, 'Christian Medical College Vellore', 'College', 'Neurology', 'Professor', 'Neurology', 'Vellore', '20260404', 1, 'Closed'),
(143, 'Christian Medical College Vellore', 'College', 'Surgery', 'Senior Resident', 'General Surgery', 'Vellore', '20260406', 3, 'Open'),
(144, 'Christian Medical College Vellore', 'College', 'Anaesthesia', 'Assistant Professor', 'Anaesthesiology', 'Vellore', '20260408', 2, 'Open'),
(145, 'St Johns Medical College', 'College', 'Palliative Medicine', 'Associate Professor', 'Palliative Medicine', 'Bengaluru', '20260410', 1, 'Open'),
(146, 'St Johns Medical College', 'College', 'General Medicine', 'Assistant Professor', 'Internal Medicine', 'Bengaluru', '20260412', 2, 'Open'),
(147, 'Kasturba Medical College Manipal', 'College', 'Orthopaedics', 'Professor', 'Orthopaedics', 'Manipal', '20260414', 1, 'Open'),
(148, 'Kasturba Medical College Manipal', 'College', 'Radiology', 'Senior Resident', 'Radio Diagnosis', 'Manipal', '20260416', 3, 'Open'),
(149, 'JIPMER', 'College', 'Pharmacology', 'Assistant Professor', 'Pharmacology', 'Puducherry', '20260418', 2, 'Open'),
(150, 'JIPMER', 'College', 'Community Medicine', 'Associate Professor', 'Community Medicine', 'Puducherry', '20260420', 1, 'Open'),
(151, 'IMS BHU', 'College', 'General Surgery', 'Professor', 'General Surgery', 'Varanasi', '20260422', 1, 'Open'),
(152, 'IMS BHU', 'College', 'Dermatology', 'Senior Resident', 'Dermatology', 'Varanasi', '20260424', 3, 'Open'),
(153, 'Apollo Hospital Delhi', 'Hospital', 'Cardiology', 'Consultant', 'Cardiology', 'Delhi', '20260425', 2, 'Open'),
(154, 'Fortis Escorts Hospital', 'Hospital', 'Neurology', 'Consultant', 'Neurology', 'Delhi', '20260425', 1, 'Open'),
(155, 'Max Super Speciality Hospital', 'Hospital', 'Emergency', 'Medical Officer', 'Emergency Medicine', 'Delhi', '20260425', 2, 'Open'),
(156, 'BLK-Max Super Speciality Hospital', 'Hospital', 'General Surgery', 'Consultant', 'General Surgery', 'Delhi', '20260425', 1, 'Open'),
(157, 'Sir Ganga Ram Hospital', 'Hospital', 'Nephrology', 'Consultant', 'Nephrology', 'Delhi', '20260425', 1, 'Open'),
(158, 'Ram Manohar Lohia Hospital', 'Hospital', 'Emergency', 'Medical Officer', 'Emergency Medicine', 'Delhi', '20260425', 2, 'Open'),
(159, 'Medanta The Medicity', 'Hospital', 'Cardiology', 'Consultant', 'Cardiology', 'Gurugram', '20260425', 1, 'Open'),
(160, 'Medanta The Medicity', 'Hospital', 'Neurology', 'Senior Resident', 'Neurology', 'Gurugram', '20260425', 2, 'Open');

CREATE TABLE Candidates (
    Candidate_name        VARCHAR(100) NOT NULL,
    Phone                 VARCHAR(15),
    Email                 VARCHAR(100) NOT NULL,
    City                  VARCHAR(50),
    Preferred_Location    VARCHAR(70),
    Qualification         VARCHAR(100) NOT NULL,
    Specialization        VARCHAR(100) NOT NULL,
    Experience_years      INT          NOT NULL,
    Source                VARCHAR(50)  NOT NULL,
    Target_institution    VARCHAR(100)  NOT NULL,
    Current_position      VARCHAR(70)  NOT NULL,
    SR_years              INT          NOT NULL DEFAULT 0,
    Ap_years              INT          NOT NULL DEFAULT 0,
    Assoc_prof_years      INT          NOT NULL DEFAULT 0,
    Status_of_BCBR_MET    VARCHAR(10)  NOT NULL DEFAULT 'No',
    CONSTRAINT PK_Candidates PRIMARY KEY (Candidate_name, Email)
);


INSERT INTO Candidates
(Candidate_name, Phone, Email, City, Preferred_Location, Qualification, Specialization, Experience_years, Source, Target_institution, Current_position, SR_years, Ap_years, Assoc_prof_years, Status_of_BCBR_MET)
VALUES
('Rahul Sharma', '9876543210', 'rahul.sharma@email.com', 'Delhi', 'Delhi', 'MBBS', 'General Medicine', 1, 'Campus', 'AIIMS', 'Senior Resident', 1, 0, 0, 'No'),
('Priya Patel', '9876543211', 'priya.patel@email.com', 'Lucknow', 'Lucknow', 'MBBS', 'Paediatrics', 1, 'Campus', 'KGMU', 'Senior Resident', 1, 0, 0, 'No'),
('Karan Gupta', '9876543212', 'karan.gupta@email.com', 'Mumbai', 'Mumbai', 'MBBS', 'Ophthalmology', 1, 'Campus', 'Grant Medical College', 'Senior Resident', 1, 0, 0, 'No'),
('Ananya Kumar', '9876543213', 'ananya.kumar@email.com', 'Chennai', 'Chennai', 'MBBS', 'ENT', 1, 'Campus', 'Madras Medical College', 'Senior Resident', 1, 0, 0, 'No'),
('Neha Verma', '9876543214', 'neha.verma@email.com', 'Ahmedabad', 'Ahmedabad', 'MBBS', 'Dermatology', 1, 'Campus', 'B.J. Medical College', 'Senior Resident', 1, 0, 0, 'No'),
('Suresh Reddy', '9876543215', 'suresh.reddy@email.com', 'Hyderabad', 'Hyderabad', 'MBBS', 'Radiology', 1, 'Campus', 'Nizam’s Institute', 'Senior Resident', 1, 0, 0, 'No'),
('Pooja Mehta', '9876543216', 'pooja.mehta@email.com', 'Bengaluru', 'Bengaluru', 'MBBS', 'Surgery', 1, 'Campus', 'St Johns Medical College', 'Senior Resident', 1, 0, 0, 'No'),
('Rajesh Iyer', '9876543217', 'rajesh.iyer@email.com', 'Kochi', 'Kochi', 'MBBS', 'Anaesthesia', 1, 'Campus', 'Amrita School of Medicine', 'Senior Resident', 1, 0, 0, 'No'),
('Monika Desai', '9876543218', 'monika.desai@email.com', 'Varanasi', 'Varanasi', 'MBBS', 'Medicine', 1, 'Campus', 'IMS BHU', 'Senior Resident', 1, 0, 0, 'No'),
('Amit Singh', '9876543219', 'amit.singh@email.com', 'Pune', 'Pune', 'MBBS', 'Paediatrics', 1, 'Campus', 'B.J. Medical College', 'Senior Resident', 1, 0, 0, 'No'),
('Divya Rani', '9876543220', 'divya.rani@email.com', 'Jaipur', 'Jaipur', 'MBBS', 'Obstetrics & Gynaecology', 1, 'Campus', 'SMS Medical College', 'Senior Resident', 1, 0, 0, 'No'),
('Vikram Malhotra', '9876543221', 'vikram.malhotra@email.com', 'Patna', 'Patna', 'MBBS', 'Medicine', 1, 'Campus', 'Patna Medical College', 'Senior Resident', 1, 0, 0, 'No'),
('Anjali Gupta', '9876543222', 'anjali.gupta@email.com', 'Delhi', 'Delhi', 'MD', 'Anatomy', 5, 'Campus', 'AIIMS', 'Assistant Professor', 1, 4, 0, 'Yes'),
('Rohit Khanna', '9876543223', 'rohit.khanna@email.com', 'Lucknow', 'Lucknow', 'MD', 'Physiology', 5, 'Campus', 'KGMU', 'Assistant Professor', 1, 4, 0, 'Yes'),
('Nandini Roy', '9876543224', 'nandini.roy@email.com', 'Mumbai', 'Mumbai', 'MD', 'Biochemistry', 5, 'Campus', 'Grant Medical College', 'Assistant Professor', 1, 4, 0, 'Yes'),
('Siddharth Joshi', '9876543225', 'siddharth.joshi@email.com', 'Chennai', 'Chennai', 'MD', 'Pharmacology', 5, 'Campus', 'Stanley Medical College', 'Assistant Professor', 1, 4, 0, 'Yes'),
('Kavita Singh', '9876543226', 'kavita.singh@email.com', 'Ahmedabad', 'Ahmedabad', 'MD', 'Pathology', 5, 'Campus', 'B.J. Medical College', 'Assistant Professor', 1, 4, 0, 'Yes'),
('Manoj Desai', '9876543227', 'manoj.desai@email.com', 'Hyderabad', 'Hyderabad', 'MD', 'Microbiology', 5, 'Campus', 'Nizam’s Institute', 'Assistant Professor', 1, 4, 0, 'Yes'),
('Shweta Reddy', '9876543228', 'shweta.reddy@email.com', 'Bengaluru', 'Bengaluru', 'MD', 'Community Medicine', 5, 'Campus', 'St Johns Medical College', 'Assistant Professor', 1, 4, 0, 'Yes'),
('Deepak Nair', '9876543229', 'deepak.nair@email.com', 'Kochi', 'Kochi', 'MD', 'Radiology', 5, 'Campus', 'Amrita School of Medicine', 'Assistant Professor', 1, 4, 0, 'Yes'),
('Meera Joshi', '9876543230', 'meera.joshi@email.com', 'Varanasi', 'Varanasi', 'MD', 'Surgery', 5, 'Campus', 'IMS BHU', 'Assistant Professor', 1, 4, 0, 'Yes'),
('Ravi Kumar', '9876543231', 'ravi.kumar@email.com', 'Pune', 'Pune', 'MD', 'Paediatrics', 5, 'Campus', 'B.J. Medical College', 'Assistant Professor', 1, 4, 0, 'Yes'),
('Preeti Verma', '9876543232', 'preeti.verma@email.com', 'Jaipur', 'Jaipur', 'MD', 'ENT', 5, 'Campus', 'SMS Medical College', 'Assistant Professor', 1, 4, 0, 'Yes'),
('Arun Sharma', '9876543233', 'arun.sharma@email.com', 'Patna', 'Patna', 'MD', 'Medicine', 5, 'Campus', 'Patna Medical College', 'Assistant Professor', 1, 4, 0, 'Yes'),
('Kriti Reddy', '9876543234', 'kriti.reddy@email.com', 'Puducherry', 'Puducherry', 'MD', 'Pharmacology', 5, 'Campus', 'JIPMER', 'Assistant Professor', 1, 4, 0, 'Yes'),
('Nikhil Mehta', '9876543235', 'nikhil.mehta@email.com', 'Kozhikode', 'Kozhikode', 'MD', 'Dermatology', 5, 'Campus', 'Government Medical College Kozhikode', 'Assistant Professor', 1, 4, 0, 'Yes'),
('Dr. Arun Banerjee', '9876543236', 'arun.banerjee@email.com', 'Delhi', 'Delhi', 'MD, DM', 'Cardiology', 8, 'Campus', 'AIIMS', 'Associate Professor', 1, 4, 3, 'Yes'),
('Dr. Priyanka Nair', '9876543237', 'priyanka.nair@email.com', 'Lucknow', 'Lucknow', 'MD', 'Radiology', 8, 'Campus', 'KGMU', 'Associate Professor', 1, 4, 3, 'Yes'),
('Dr. Sanjay Mehta', '9876543238', 'sanjay.mehta@email.com', 'Mumbai', 'Mumbai', 'MD', 'Ophthalmology', 8, 'Campus', 'Grant Medical College', 'Associate Professor', 1, 4, 3, 'Yes'),
('Dr. Meenakshi Rao', '9876543239', 'meenakshi.rao@email.com', 'Chennai', 'Chennai', 'MD', 'Obstetrics & Gynaecology', 8, 'Campus', 'Madras Medical College', 'Associate Professor', 1, 4, 3, 'Yes'),
('Dr. Rakesh Varma', '9876543240', 'rakesh.varma@email.com', 'Ahmedabad', 'Ahmedabad', 'MD', 'Dermatology', 8, 'Campus', 'B.J. Medical College', 'Associate Professor', 1, 4, 3, 'Yes'),
('Dr. Sunita Pillai', '9876543241', 'sunita.pillai@email.com', 'Hyderabad', 'Hyderabad', 'MD', 'Neurology', 8, 'Campus', 'Nizam’s Institute', 'Associate Professor', 1, 4, 3, 'Yes'),
('Dr. Vikas Dubey', '9876543242', 'vikas.dubey@email.com', 'Bengaluru', 'Bengaluru', 'MD', 'Surgery', 8, 'Campus', 'St Johns Medical College', 'Associate Professor', 1, 4, 3, 'Yes'),
('Dr. Roshan Thomas', '9876543243', 'roshan.thomas@email.com', 'Kochi', 'Kochi', 'MD', 'Anaesthesia', 8, 'Campus', 'Amrita School of Medicine', 'Associate Professor', 1, 4, 3, 'Yes'),
('Dr. Anil Kumar', '9876543244', 'anil.kumar@email.com', 'Varanasi', 'Varanasi', 'MD', 'Medicine', 8, 'Campus', 'IMS BHU', 'Associate Professor', 1, 4, 3, 'Yes'),
('Dr. Jyoti Malhotra', '9876543245', 'jyoti.malhotra@email.com', 'Pune', 'Pune', 'MD', 'Paediatrics', 8, 'Campus', 'B.J. Medical College', 'Associate Professor', 1, 4, 3, 'Yes'),
('Dr. Sanjay Singh', '9876543246', 'sanjay.singh@email.com', 'Jaipur', 'Jaipur', 'MD', 'ENT', 8, 'Campus', 'SMS Medical College', 'Associate Professor', 1, 4, 3, 'Yes'),
('Dr. Neha Deshmukh', '9876543247', 'neha.deshmukh@email.com', 'Patna', 'Patna', 'MD', 'Medicine', 8, 'Campus', 'Patna Medical College', 'Associate Professor', 1, 4, 3, 'Yes'),
('Dr. Ravi Shankar', '9876543248', 'ravi.shankar@email.com', 'Puducherry', 'Puducherry', 'MD', 'Community Medicine', 8, 'Campus', 'JIPMER', 'Associate Professor', 1, 4, 3, 'Yes'),
('Dr. Shweta Iyer', '9876543249', 'shweta.iyer@email.com', 'Kozhikode', 'Kozhikode', 'MD', 'Psychiatry', 8, 'Campus', 'Government Medical College Kozhikode', 'Associate Professor', 1, 4, 3, 'Yes'),
('Prof. Manoj Sharma', '9876543250', 'manoj.sharma@email.com', 'Delhi', 'Delhi', 'MD, DM', 'Medicine', 12, 'Campus', 'AIIMS', 'Professor', 1, 4, 7, 'Yes'),
('Prof. Ramesh Kumar', '9876543251', 'ramesh.kumar@email.com', 'Lucknow', 'Lucknow', 'MD, DM', 'Neurology', 11, 'Campus', 'KGMU', 'Professor', 1, 4, 7, 'Yes'),
('Prof. Suresh Reddy', '9876543252', 'suresh.reddy@email.com', 'Mumbai', 'Mumbai', 'MD, DM', 'Cardiology', 12, 'Campus', 'Tata Memorial', 'Professor', 1, 4, 8, 'Yes'),
('Prof. Anjali Desai', '9876543253', 'anjali.desai@email.com', 'Chennai', 'Chennai', 'MD, DM', 'Gastroenterology', 11, 'Campus', 'Madras Medical College', 'Professor', 1, 4, 7, 'Yes'),
('Prof. Ravi Malhotra', '9876543254', 'ravi.malhotra@email.com', 'Ahmedabad', 'Ahmedabad', 'MD, DM', 'Paediatrics', 12, 'Campus', 'B.J. Medical College', 'Professor', 1, 4, 8, 'Yes'),
('Prof. Priya Iyer', '9876543255', 'priya.iyer@email.com', 'Hyderabad', 'Hyderabad', 'MD, DM', 'Nephrology', 11, 'Campus', 'Nizam’s Institute', 'Professor', 1, 4, 7, 'Yes'),
('Prof. Raghav Sharma', '9876543256', 'raghav.sharma@email.com', 'Bengaluru', 'Bengaluru', 'MD, DM', 'Cardiology', 12, 'Campus', 'St Johns Medical College', 'Professor', 1, 4, 8, 'Yes'),
('Prof. Meera Nair', '9876543257', 'meera.nair@email.com', 'Kochi', 'Kochi', 'MD, DM', 'Oncology', 11, 'Campus', 'Amrita School of Medicine', 'Professor', 1, 4, 7, 'Yes'),
('Prof. Vikram Verma', '9876543258', 'vikram.verma@email.com', 'Varanasi', 'Varanasi', 'MD, DM', 'Medicine', 12, 'Campus', 'IMS BHU', 'Professor', 1, 4, 8, 'Yes'),
('Prof. Ananya Joshi', '9876543259', 'ananya.joshi@email.com', 'Patna', 'Patna', 'MD, DM', 'Surgery', 11, 'Campus', 'Patna Medical College', 'Professor', 1, 4, 7, 'Yes');




CREATE TABLE Applications (
    Job_Id                    INT NULL,
    Application_id            INT IDENTITY(1,1) NOT NULL,
    Candidate_name            VARCHAR(100) NOT NULL,
    Email                     VARCHAR(100) NOT NULL,
    Applied_date              DATE NOT NULL,
    Current_role              VARCHAR(100) NOT NULL,
    Current_salary_package    DECIMAL(10,2) NOT NULL,
    Job_role                  VARCHAR(100) NOT NULL,
    Expected_salary_package   DECIMAL(10,2) NOT NULL,
    Job_type                  VARCHAR(20) NOT NULL,
    Application_status        VARCHAR(30) NOT NULL,
    Offer_from                VARCHAR(100) NULL,
    Offered_locations         VARCHAR(200) NULL,
    Hired_at                  VARCHAR(100) NULL,
    Hired_location            VARCHAR(100) NULL,
    Current_location          VARCHAR(50) NULL,
    Preferred_location        VARCHAR(50) NULL,
    Offered_salary_package    DECIMAL(10,2) NULL,
    Final_salary_package      DECIMAL(10,2) NULL,
    Exam_status               VARCHAR(10) NOT NULL,
    CONSTRAINT PK_Applications PRIMARY KEY (Application_id),
    CONSTRAINT FK_Applications_Jobs FOREIGN KEY (Job_Id) REFERENCES Jobs (Job_Id)
    );

INSERT INTO Candidates
(Candidate_name, Phone, Email, City, Preferred_Location, Qualification, Specialization, Experience_years, Source, Target_institution, Current_position, SR_years, Ap_years, Assoc_prof_years, Status_of_BCBR_MET)
VALUES
('Ananya Sharma', '9810100001', 'ananya.sharma01@gmail.com', 'Delhi', 'Delhi', 'MD', 'Anatomy', 1, 'LinkedIn', 'College', 'Senior Resident', 1, 0, 0, 'No'),
('Rohit Verma', '9810100002', 'rohit.verma02@gmail.com', 'Delhi', 'Delhi', 'MD', 'Physiology', 5, 'Referral', 'College', 'Assistant Professor', 1, 4, 0, 'Yes'),
('Priya Gupta', '9810100003', 'priya.gupta03@gmail.com', 'Delhi', 'Delhi', 'MD', 'Biochemistry', 1, 'Job Portal', 'College', 'Senior Resident', 1, 0, 0, 'No'),
('Karan Mehta', '9810100004', 'karan.mehta04@gmail.com', 'Delhi', 'Delhi', 'MD', 'Internal Medicine', 10, 'Agency', 'College', 'Professor', 1, 4, 5, 'Yes'),
('Neha Reddy', '9810100005', 'neha.reddy05@gmail.com', 'Mumbai', 'Mumbai', 'MD', 'Pathology', 1, 'LinkedIn', 'College', 'Senior Resident', 1, 0, 0, 'No'),
('Arjun Singh', '9810100006', 'arjun.singh06@gmail.com', 'Lucknow', 'Lucknow', 'MD', 'Pharmacology', 8, 'Referral', 'College', 'Associate Professor', 1, 4, 3, 'Yes'),
('Sneha Iyer', '9810100007', 'sneha.iyer07@gmail.com', 'Chennai', 'Chennai', 'MD', 'Microbiology', 1, 'Job Portal', 'College', 'Senior Resident', 1, 0, 0, 'No'),
('Vikram Joshi', '9810100008', 'vikram.joshi08@gmail.com', 'Lucknow', 'Lucknow', 'MD', 'Community Medicine', 8, 'Agency', 'College', 'Associate Professor', 1, 4, 3, 'Yes'),
('Pooja Nair', '9810100009', 'pooja.nair09@gmail.com', 'Delhi', 'Delhi', 'MD', 'Ophthalmology', 5, 'LinkedIn', 'College', 'Assistant Professor', 1, 4, 0, 'Yes'),
('Rahul Das', '9810100010', 'rahul.das10@gmail.com', 'Kolkata', 'Delhi', 'MD', 'ENT', 1, 'Referral', 'College', 'Senior Resident', 1, 0, 0, 'No'),
('Meera Kapoor', '9810100011', 'meera.kapoor11@gmail.com', 'Delhi', 'Delhi', 'MD', 'Paediatrics', 1, 'Job Portal', 'College', 'Senior Resident', 1, 0, 0, 'No'),
('Sahil Khan', '9810100012', 'sahil.khan12@gmail.com', 'Hyderabad', 'Hyderabad', 'MD', 'Radiology', 5, 'Agency', 'College', 'Assistant Professor', 1, 4, 0, 'Yes'),
('Isha Malhotra', '9810100013', 'isha.malhotra13@gmail.com', 'Delhi', 'Delhi', 'MD', 'Psychiatry', 1, 'LinkedIn', 'College', 'Senior Resident', 1, 0, 0, 'No'),
('Aman Yadav', '9810100014', 'aman.yadav14@gmail.com', 'Chennai', 'Chennai', 'MD', 'Medicine', 12, 'Referral', 'College', 'Professor', 1, 4, 7, 'Yes'),
('Nidhi Pandey', '9810100015', 'nidhi.pandey15@gmail.com', 'Mumbai', 'Mumbai', 'MD', 'Surgery', 1, 'Job Portal', 'College', 'Senior Resident', 1, 0, 0, 'No'),
('Farhan Ali', '9810100016', 'farhan.ali16@gmail.com', 'Delhi', 'Delhi', 'MD', 'Orthopaedics', 5, 'Agency', 'College', 'Assistant Professor', 1, 4, 0, 'Yes'),
('Tanya Singh', '9810100017', 'tanya.singh17@gmail.com', 'Bengaluru', 'Bengaluru', 'MD', 'Dermatology', 1, 'LinkedIn', 'College', 'Senior Resident', 1, 0, 0, 'No'),
('Kabir Rao', '9810100018', 'kabir.rao18@gmail.com', 'Mumbai', 'Mumbai', 'MD', 'Obstetrics & Gynaecology', 11, 'Referral', 'College', 'Professor', 1, 4, 6, 'Yes'),
('Simran Khurana', '9810100019', 'simran.khurana19@gmail.com', 'Mumbai', 'Mumbai', 'MD', 'Ophthalmology', 1, 'Job Portal', 'College', 'Senior Resident', 1, 0, 0, 'No'),
('Dev Patel', '9810100020', 'dev.patel20@gmail.com', 'Ahmedabad', 'Ahmedabad', 'MD', 'Microbiology', 5, 'Agency', 'College', 'Assistant Professor', 1, 4, 0, 'Yes'),
('Riya Mehta', '9810100021', 'riya.mehta21@gmail.com', 'Delhi', 'Delhi', 'MD', 'Medical Oncology', 1, 'LinkedIn', 'College', 'Senior Resident', 1, 0, 0, 'No'),
('Akash Jain', '9810100022', 'akash.jain22@gmail.com', 'Lucknow', 'Lucknow', 'MD', 'Surgical Oncology', 8, 'Referral', 'College', 'Associate Professor', 1, 4, 3, 'Yes'),
('Mira Bose', '9810100023', 'mira.bose23@gmail.com', 'Chennai', 'Chennai', 'MD', 'Paediatrics', 1, 'Job Portal', 'College', 'Senior Resident', 1, 0, 0, 'No'),
('Suresh Kumar', '9810100024', 'suresh.kumar24@gmail.com', 'Ahmedabad', 'Ahmedabad', 'MD', 'Cardiology', 12, 'Agency', 'College', 'Professor', 1, 4, 7, 'Yes'),
('Ritu Agarwal', '9810100025', 'ritu.agarwal25@gmail.com', 'Puducherry', 'Puducherry', 'MD', 'Medicine', 1, 'LinkedIn', 'College', 'Senior Resident', 1, 0, 0, 'No'),
('Naman Sethi', '9810100026', 'naman.sethi26@gmail.com', 'Bengaluru', 'Bengaluru', 'MD', 'Surgery', 8, 'Referral', 'College', 'Associate Professor', 1, 4, 3, 'Yes'),
('Shreya Menon', '9810100027', 'shreya.menon27@gmail.com', 'Kochi', 'Kochi', 'MD', 'Dermatology', 1, 'Job Portal', 'College', 'Senior Resident', 1, 0, 0, 'No'),
('Deepak Rana', '9810100028', 'deepak.rana28@gmail.com', 'Puducherry', 'Puducherry', 'MD', 'Paediatrics', 8, 'Agency', 'College', 'Associate Professor', 1, 4, 3, 'Yes'),
('Anita Paul', '9810100029', 'anita.paul29@gmail.com', 'Vellore', 'Vellore', 'MD', 'Anaesthesia', 1, 'LinkedIn', 'College', 'Senior Resident', 1, 0, 0, 'No'),
('Tarun Vohra', '9810100030', 'tarun.vohra30@gmail.com', 'Varanasi', 'Varanasi', 'MD', 'Radiology', 5, 'Referral', 'College', 'Assistant Professor', 1, 4, 0, 'Yes'),
('Kavya Sharma', '9810100031', 'kavya.sharma31@gmail.com', 'Delhi', 'Delhi', 'MD', 'Orthopaedics', 1, 'Job Portal', 'College', 'Senior Resident', 1, 0, 0, 'No'),
('Mohit Arora', '9810100032', 'mohit.arora32@gmail.com', 'Mumbai', 'Mumbai', 'MD', 'General Medicine', 8, 'Agency', 'College', 'Associate Professor', 1, 4, 3, 'Yes'),
('Anusha Rao', '9810100033', 'anusha.rao33@gmail.com', 'Manipal', 'Manipal', 'MD', 'ENT', 1, 'LinkedIn', 'College', 'Senior Resident', 1, 0, 0, 'No'),
('Rajat Bhatia', '9810100034', 'rajat.bhatia34@gmail.com', 'Varanasi', 'Varanasi', 'MD', 'Dermatology', 11, 'Referral', 'College', 'Professor', 1, 4, 6, 'Yes'),
('Neelam Verma', '9810100035', 'neelam.verma35@gmail.com', 'Chennai', 'Chennai', 'MD', 'Radiology', 1, 'Job Portal', 'College', 'Senior Resident', 1, 0, 0, 'No'),
('Aakash Singh', '9810100036', 'aakash.singh36@gmail.com', 'Delhi', 'Delhi', 'MD', 'Medicine', 5, 'Agency', 'College', 'Assistant Professor', 1, 4, 0, 'Yes'),
('Pallavi Jain', '9810100037', 'pallavi.jain37@gmail.com', 'Hyderabad', 'Hyderabad', 'MD', 'Psychiatry', 1, 'LinkedIn', 'College', 'Senior Resident', 1, 0, 0, 'No'),
('Sanjay Khanna', '9810100038', 'sanjay.khanna38@gmail.com', 'Delhi', 'Delhi', 'MD', 'Dermatology', 12, 'Referral', 'College', 'Professor', 1, 4, 7, 'Yes'),
('Divya Nair', '9810100039', 'divya.nair39@gmail.com', 'Lucknow', 'Lucknow', 'MD', 'Medicine', 1, 'Job Portal', 'College', 'Senior Resident', 1, 0, 0, 'No'),
('Harsh Malhotra', '9810100040', 'harsh.malhotra40@gmail.com', 'Mumbai', 'Mumbai', 'MD', 'Surgery', 8, 'Agency', 'College', 'Associate Professor', 1, 4, 3, 'Yes'),
('Sana Khan', '9810100041', 'sana.khan41@gmail.com', 'Delhi', 'Delhi', 'MD', 'Psychiatry', 1, 'LinkedIn', 'College', 'Senior Resident', 1, 0, 0, 'No'),
('Prateek Gupta', '9810100042', 'prateek.gupta42@gmail.com', 'Chennai', 'Chennai', 'MD', 'Dermatology', 5, 'Referral', 'College', 'Assistant Professor', 1, 4, 0, 'Yes'),
('Ayesha Siddiqui', '9810100043', 'ayesha.siddiqui43@gmail.com', 'Chennai', 'Chennai', 'MD', 'Medicine', 1, 'Job Portal', 'College', 'Senior Resident', 1, 0, 0, 'No'),
('Gaurav Sinha', '9810100044', 'gaurav.sinha44@gmail.com', 'Chennai', 'Chennai', 'MD', 'Surgery', 13, 'Agency', 'College', 'Professor', 1, 4, 8, 'Yes'),
('Mansi Jain', '9810100045', 'mansi.jain45@gmail.com', 'Ahmedabad', 'Ahmedabad', 'MD', 'Orthopaedics', 1, 'LinkedIn', 'College', 'Senior Resident', 1, 0, 0, 'No'),
('Yash Raj', '9810100046', 'yash.raj46@gmail.com', 'Delhi', 'Delhi', 'MD', 'ENT', 5, 'Referral', 'College', 'Assistant Professor', 1, 4, 0, 'Yes'),
('Komal Seth', '9810100047', 'komal.seth47@gmail.com', 'Mumbai', 'Mumbai', 'MD', 'Dermatology', 1, 'Job Portal', 'College', 'Senior Resident', 1, 0, 0, 'No'),
('Rahul Sood', '9810100048', 'rahul.sood48@gmail.com', 'Vellore', 'Vellore', 'MD', 'Radiology', 10, 'Agency', 'College', 'Professor', 1, 4, 5, 'Yes'),
('Ira Dutta', '9810100049', 'ira.dutta49@gmail.com', 'Puducherry', 'Puducherry', 'MD', 'Medicine', 1, 'LinkedIn', 'College', 'Senior Resident', 1, 0, 0, 'No'),
('Siddharth Rao', '9810100050', 'siddharth.rao50@gmail.com', 'Kochi', 'Kochi', 'MD', 'Surgery', 5, 'Referral', 'College', 'Assistant Professor', 1, 4, 0, 'Yes'),
('Bhavna Joshi', '9810100051', 'bhavna.joshi51@gmail.com', 'Delhi', 'Delhi', 'MD', 'Orthopaedics', 1, 'Job Portal', 'College', 'Senior Resident', 1, 0, 0, 'No'),
('Varun Kapoor', '9810100052', 'varun.kapoor52@gmail.com', 'Lucknow', 'Lucknow', 'MD', 'General Medicine', 8, 'Agency', 'College', 'Associate Professor', 1, 4, 3, 'Yes'),
('Naina Roy', '9810100053', 'naina.roy53@gmail.com', 'Ahmedabad', 'Ahmedabad', 'MD', 'Palliative Medicine', 1, 'LinkedIn', 'College', 'Senior Resident', 1, 0, 0, 'No'),
('Arun Thomas', '9810100054', 'arun.thomas54@gmail.com', 'Kozhikode', 'Kozhikode', 'MD', 'General Surgery', 11, 'Referral', 'College', 'Professor', 1, 4, 6, 'Yes'),
('Madhuri Das', '9810100055', 'madhuri.das55@gmail.com', 'Bengaluru', 'Bengaluru', 'MD', 'Orthopaedics', 1, 'Job Portal', 'College', 'Senior Resident', 1, 0, 0, 'No'),
('Kunal Suri', '9810100056', 'kunal.suri56@gmail.com', 'Puducherry', 'Puducherry', 'MD', 'Pharmacology', 5, 'Agency', 'College', 'Assistant Professor', 1, 4, 0, 'Yes'),
('Prachi Singh', '9810100057', 'prachi.singh57@gmail.com', 'Varanasi', 'Varanasi', 'MD', 'Community Medicine', 1, 'LinkedIn', 'College', 'Senior Resident', 1, 0, 0, 'No'),
('Ramesh Iyer', '9810100058', 'ramesh.iyer58@gmail.com', 'Varanasi', 'Varanasi', 'MD', 'General Surgery', 10, 'Referral', 'College', 'Professor', 1, 4, 5, 'Yes'),
('Swati Paul', '9810100059', 'swati.paul59@gmail.com', 'Kochi', 'Kochi', 'MD', 'Orthopaedics', 1, 'Job Portal', 'College', 'Senior Resident', 1, 0, 0, 'No'),
('Om Prakash', '9810100060', 'om.prakash60@gmail.com', 'Delhi', 'Delhi', 'MD', 'Dermatology', 5, 'Agency', 'College', 'Assistant Professor', 1, 4, 0, 'Yes');

